branches:
  only:
    - master
language: android
jdk: oraclejdk8
dist: trusty
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
if: "(branch = master AND type = push) OR (head_branch != master AND type = pull_request)"
install:
  - "./travis/install.sh"
stages:
  - name: Building Project
  - name: Running Tests
    if: branch = master AND type = push
jobs:
  include:
    - stage: Building Project
      script: "./gradlew check"
      env: JOB=Build
    - script: "./gradlew detekt"
      env: JOB=Linter